import sys
sys.stdout.reconfigure(encoding='utf-8')

lines = [
"# TODO Fakemetre - Images a generer avec ChatGPT / DALL-E",
"",
"> Coller ces prompts dans ChatGPT (GPT-4o avec generation d'images).",
"> Sauvegarder dans images/NOM_FICHIER.png",
"> Puis ajouter img:\"images/NOM_FICHIER.png\" dans la source JS correspondante.",
"",
"---",
"",
"## FILMS ET DOCUMENTAIRES",
"",
"### film_aventure_survie.png",
"FR: Capture d'ecran stylisee d'un film hollywoodien de survie. Personnage buvant de l'eau de cactus dans un desert aride. Style cinema annees 2010, grain cinematographique, letterbox noir. Aucun texte visible.",
"EN: Cinematic screenshot of a Hollywood survival film. Character drinking water from a cactus in an arid desert. 2010s film style, cinema grain, black letterbox. No visible text.",
"",
"### film_edison_biopic.png",
"FR: Affiche de biopic hollywoodien fictif sur un inventeur du XIXe siecle. Couleurs sepia/dorees, silhouette d'homme tenant une ampoule. Titre fictif \"LE GENIE\". Aucun nom reel.",
"EN: Fictional Hollywood biopic poster about a 19th-century inventor. Sepia/golden palette, silhouette of man holding a light bulb. Fictional title \"THE GENIUS\". No real names.",
"",
"### film_colomb_historique.png",
"FR: Affiche de film historique fictif sur la decouverte de l'Amerique. Style annees 1990, bateaux a voile sur ocean tumultueux au coucher du soleil. Titre fictif \"LA GRANDE DECOUVERTE\".",
"EN: Fictional historical film poster about the Age of Exploration. 1990s style, sailing ships on stormy ocean at sunset. Fictional title \"THE GREAT DISCOVERY\".",
"",
"### docu_netflix_plastique.png",
"FR: Miniature de documentaire Netflix fictif sur la pollution plastique. Tortue de mer entouree de dechets plastiques sous l'eau. Interface Netflix simulee, titre fictif \"PLASTIQUE - LA GRANDE VAGUE\".",
"EN: Fictional Netflix documentary thumbnail. Sea turtle surrounded by plastic waste underwater. Simulated Netflix interface, fictional title \"PLASTIC - THE GREAT WAVE\".",
"",
"### docu_vaxxed.png",
"FR: Miniature de documentaire fictif anti-vaccin conspirationniste. Fond sombre, seringue en gros plan, texte alarmiste. Titre fictif \"VAXXED - LA VERITE CACHEE\". Aucune reference medicale reelle.",
"EN: Fictional anti-vaccine conspiracy documentary thumbnail. Dark background, close-up syringe, alarming text. Fictional title \"VAXXED - THE HIDDEN TRUTH\". No real medical references.",
"",
"### docu_sucre_netflix.png",
"FR: Miniature Netflix fictif sur les effets du sucre. Tas de sucre blanc et aliments ultra-transformes colores. Titre fictif \"CE QUE LE SUCRE VOUS FAIT\".",
"EN: Fictional Netflix thumbnail about sugar effects. Pile of white sugar and colorful ultra-processed foods. Fictional title \"WHAT SUGAR DOES TO YOU\".",
"",
"### emission_tv_annees80.png",
"FR: Capture simulee d'une emission de vulgarisation TV des annees 1980. Qualite video vintage, distorsion CRT, presentateur en costume beige devant des images d'animaux. Ambiance nostalgique.",
"EN: Simulated 1980s science TV show screenshot. Vintage video quality, CRT distortion, presenter in beige suit in front of animal footage. Nostalgic atmosphere.",
"",
"### opera_wagner_vikings.png",
"FR: Illustration d'une scene d'opera XIXe siecle avec des Vikings aux casques a cornes. Style gravure victorienne, costumes theatraux exageres, sepia/rouge sombre. Representation romantique fictive.",
"EN: 19th-century opera scene illustration with horned-helmet Vikings. Victorian engraving style, exaggerated theatrical costumes, sepia/dark red. Romantic fictional depiction.",
"",
"### jeu_video_vikings.png",
"FR: Capture d'un jeu video fictif de combat medieval. Vikings avec casques a cornes spectaculaires. Style fantasy annees 2010, couleurs saturees, HUD visible. Titre fictif \"AGE OF VIKINGS II\".",
"EN: Fictional medieval combat video game screenshot. Vikings with spectacular horned helmets. Fantasy 2010s style, saturated colors, HUD visible. Fictional title \"AGE OF VIKINGS II\".",
"",
"### ted_conference.png",
"FR: Photo simulee d'une conference TED. Oratrice sur scene rouge TED, logo TED en grand, fond noir. Femme presentant des diapositives de cerveaux. Style conference scientifique.",
"EN: Simulated TED talk photo. Female speaker on red TED stage, large TED logo, black background. Woman presenting brain slides. Scientific conference style.",
"",
"### youtube_gaming_thumbnail.png",
"FR: Miniature YouTube fictive d'un influenceur gaming. Fond colore flashy, jeune homme enthousiaste avec casque gamer. Texte fictif \"LES JEUX VIDEO C'EST QUE DU BON !!\". Style clickbait, 2.3M vues.",
"EN: Fictional YouTube gaming influencer thumbnail. Flashy colorful background, enthusiastic young man with gaming headset. Fictional text \"GAMING IS ONLY GOOD!!\". Clickbait style, 2.3M views shown.",
"",
"### caricature_napoleon.png",
"FR: Caricature politique style gravure britannique XIXe siecle. Napoleon Bonaparte represente comme un personnage petit et ridicule. Style James Gillray, encre noire et lavis, humour satirique.",
"EN: Political caricature in 19th-century British engraving style. Napoleon Bonaparte depicted as small and ridiculous. James Gillray style, black ink and wash, satirical humor.",
"",
"---",
"",
"## LIVRES ET MANUELS",
"",
"### livre_larousse_junior.png",
"FR: Photo d'une encyclopedie Larousse Junior fictive vintage des annees 1990. Couverture cartonee usee, couleurs primaires annees 90, illustration d'enfants et planetes. Titre fictif \"LAROUSSE JUNIOR\".",
"EN: Photo of a fictional vintage 1990s Larousse Junior encyclopedia. Worn hardcover, 90s primary colors, illustration of children and planets. Fictional title \"LAROUSSE JUNIOR\".",
"",
"### manuel_sciences_1950.png",
"FR: Photo d'un vieux manuel scolaire fictif des annees 1950. Couverture cartonee usee brun/beige, dessins scientifiques de plantes et animaux. Pages jaunies. Titre fictif \"SCIENCES NATURELLES - Cours elementaire\".",
"EN: Photo of a worn fictional 1950s science textbook. Brown/beige worn hardcover, scientific plant and animal drawings. Yellowed pages. Fictional title \"NATURAL SCIENCES - Elementary Course\".",
"",
"### livre_wheat_belly.png",
"FR: Couverture de livre de regime fictif anti-gluten style best-seller americain. Couleurs vertes/blanches, baguette avec panneau interdit. Titre fictif \"WHEAT BELLY\" par \"Dr W. Davis\".",
"EN: Fictional American anti-gluten diet book cover. Green/white colors, baguette with forbidden sign. Fictional title \"WHEAT BELLY\" by \"Dr W. Davis\".",
"",
"### livre_fabriquecretin.png",
"FR: Couverture de livre de neurosciences grand public fictif. Fond blanc, cerveau avec smartphone a la place. Titre fictif \"LA FABRIQUE DU CRETIN DIGITAL\" par \"M. Desmurget\".",
"EN: Fictional popular neuroscience book cover. White background, brain with smartphone instead. Fictional title \"THE DIGITAL IDIOT FACTORY\" by \"M. Desmurget\".",
"",
"---",
"",
"## PUBLICITES",
"",
"### pub_tv_eau_bouteille.png",
"FR: Capture de pub TV fictive pour eau en bouteille \"AquaVita\". Personne sportive buvant de l'eau en montagne. Slogan fictif \"L'eau pure pour une vie pure\". Style pub TV francaise annees 2010.",
"EN: Fictional TV ad screenshot for bottled water \"AquaVita\". Athletic person drinking water in mountains. Fictional slogan \"Pure water for a pure life\". French 2010s TV ad style.",
"",
"### emballage_carottes_bio.png",
"FR: Emballage de carottes bio fictif. Couleurs orange/vert, logo Bio, feuilles. Slogan fictif \"Naturellement bon pour vos yeux !\". Marque fictive \"Bio Jardin\".",
"EN: Fictional organic carrot packaging. Orange/green colors, Organic logo, leaves. Fictional slogan \"Naturally good for your eyes!\". Fictional brand \"Bio Garden\".",
"",
"### pub_sans_gluten.png",
"FR: Photo de rayon supermarche fictif \"Sans gluten\". Emballages colores avec mentions SANS GLUTEN et HEALTHY. Produits varies. Aucune marque reelle.",
"EN: Fictional supermarket gluten-free aisle photo. Colorful packaging labeled GLUTEN-FREE and HEALTHY. Various products. No real brands.",
"",
"---",
"",
"## CHECKLIST D'INTEGRATION",
"Apres generation de chaque image :",
"1. Sauvegarder dans images/NOM_FICHIER.png",
"2. Ajouter dans la source JS : img:\"images/NOM_FICHIER.png\"",
"   et imgCaption:\"Description courte de l'image\"",
"3. Tester dans le navigateur",
"4. Lancer deploy.bat",
]

with open(r'C:\Users\ASUS\Documents\Web apps\Jeux\fakemetre\TODO_Fakemetre.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
print('Written', len(lines), 'lines')
